#!/usr/bin/env python
"""Self-contained demo dataset generator used by ``homoeogwas demo``.

Writes, under ``out_dir``:
  geno/A/all.{bed,bim,fam}, geno/B/all.{bed,bim,fam}  -- two synthetic subgenomes
  pheno.tsv                                           -- one quantitative trait with a planted QTL
  demo.yaml                                           -- a runnable fit config

The data are deterministic (fixed seed) and carry no real biology; they just
exercise the full input -> fit -> output path so a new user can check their install.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

SUBS = ["A", "B"]
# Paths are filled with absolute locations at generation time so the config runs
# from any working directory; the {subgenome} template is kept literal.
DEMO_YAML = """\
# HomoeoGWAS minimal demo — generated by homoeogwas.demo_data (deterministic).
# Runnable as:  homoeogwas fit -c demo.yaml
panel:
  name: demo_allotetraploid
  subgenomes: [A, B]

phenotype:
  path: {pheno}
  sample_col: sample
  trait: y

genotype:
  scan_bed_prefix_template: {bed_tpl}
  grm:
    source: bed
    bed_prefix_template: {bed_tpl}
    maf_min: 0.01

kernels:
  normalize: trace
  include_hadamard: false

reml:
  n_starts: 3
  seed: 2026

scan:
  mode: memory
  backend: cpu
  batch_size: 20000
  maf_min: 0.01
  call_rate_min: 0.9

outputs:
  out_dir: {out_dir}
  prefix: demo
"""


def make_demo(out_dir: str | Path, *, n_samples: int = 120, n_snp: int = 250,
              n_causal: int = 6, h2: float = 0.5, seed: int = 7) -> Path:
    """Write the demo dataset into ``out_dir``; return the config path."""
    from bed_reader import to_bed

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed)
    samples = [f"line{i:03d}" for i in range(n_samples)]

    geno_by_sub: dict[str, np.ndarray] = {}
    for sub in SUBS:
        maf = rng.uniform(0.05, 0.5, size=n_snp)
        # hardcall dosage 0/1/2 ~ Binomial(2, maf), samples x snps
        g = rng.binomial(2, maf[None, :], size=(n_samples, n_snp)).astype(np.int8)
        geno_by_sub[sub] = g
        sub_dir = out / "geno" / sub
        sub_dir.mkdir(parents=True, exist_ok=True)
        # two logical chromosomes per subgenome (A1/A2, B1/B2)
        half = n_snp // 2
        chrom = np.array([f"{sub}1"] * half + [f"{sub}2"] * (n_snp - half))
        bp = np.concatenate([np.arange(1, half + 1), np.arange(1, n_snp - half + 1)]) * 1000
        props = {
            "fid": np.array(samples), "iid": np.array(samples),
            "sid": np.array([f"{sub}_snp{j:04d}" for j in range(n_snp)]),
            "chromosome": chrom, "bp_position": bp.astype(np.int32),
            "allele_1": np.array(["A"] * n_snp), "allele_2": np.array(["G"] * n_snp),
        }
        to_bed(str(sub_dir / "all.bed"), g, properties=props)

    # phenotype: additive QTL planted in both subgenomes
    allg = np.hstack([geno_by_sub[s] for s in SUBS]).astype(float)
    allg = (allg - allg.mean(0)) / (allg.std(0) + 1e-9)
    p = allg.shape[1]
    causal = rng.choice(p, size=n_causal, replace=False)
    beta = np.zeros(p)
    beta[causal] = rng.normal(0, 1, size=n_causal)
    g_eff = allg @ beta
    g_eff *= np.sqrt(h2 / (np.var(g_eff) + 1e-12))
    noise = rng.normal(0, np.sqrt(1 - h2), size=n_samples)
    y = g_eff + noise
    with open(out / "pheno.tsv", "w") as fh:
        fh.write("sample\ty\n")
        for s, v in zip(samples, y, strict=True):
            fh.write(f"{s}\t{v:.6f}\n")

    cfg_path = out / "demo.yaml"
    cfg_path.write_text(DEMO_YAML.format(
        pheno=(out / "pheno.tsv").resolve(),
        bed_tpl=str((out / "geno").resolve()) + "/{subgenome}/all",
        out_dir=(out / "demo_out").resolve(),
    ))
    return cfg_path
